from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("Cepillado",views.cepilladoInfo),
    path('cepilladoInfo',views.cepilladoInfo,name="cepilladoInfo"),
    path('trozadoInfo',views.trozadoInfo,name="trozadoInfo"),
    path("Trozado",views.trozadoInfo),
    path('secadoInfo',views.secadoInfo,name="secadoInfo"),
    path("Secado",views.secadoInfo),
    path('fingerInfo',views.fingerInfo,name="fingerInfo"),
    path("Finger",views.fingerInfo),
    path('moldureraInfo',views.moldureraInfo,name="moldureraInfo"),
    path("Moldurera",views.moldureraInfo),
    path('aserraderoInfo',views.aserraderoInfo,name="aserraderoInfo"),
    path("SalidaAserradero",views.aserraderoInfo),
    path("EntradaAserradero",views.entradaAserraderoInfo),
    path('entradaAserraderoInfo',views.entradaAserraderoInfo,name="entradaAserraderoInfo"),
    path("nuevocodigo",views.nuevoCodigo),
    path("Reproceso", views.reprocesoInfo),
    path('reprocesoInfo',views.reprocesoInfo,name="reprocesoInfo"),
    path("EntradaAserradero/",views.EntradaASEFormView.as_view(),name='entrada_aserradero'),
    path("EntradaAserradero/preview",views.previsualizacionEASE,name='previsualEASE'),
    path("SalidaAserradero/",views.AserraderoFormView.as_view(),name='salida_aserradero'),
    path("SalidaAserradero/preview",views.previsualizacion,name='previsualizacion'),
    path("Cepillado/",views.CepilladoFormView.as_view(),name='cepillado'),
    path("Cepillado/preview",views.previsualizacionCep,name='previsualCep'),
    path("Secado/",views.SecadoFormView.as_view(),name='secado'),
    path("Secado/previsualizacionSec",views.previsualizacionSec,name='previsualSec'),
    path("Trozado/",views.TrozadoFormView.as_view(),name='trozado'),
    path("Trozado/previsualizacionTRZ",views.previsualizacionTRZ,name='previsualTRZ'),
    path("Finger/",views.FingerFormView.as_view(),name='finger'),
    path("Finger/previsualizacionFNG",views.previsualizacionFNG,name='previsualFNG'),
    path("Moldurera/",views.MoldureraFormView.as_view(),name='moldurera'),
    path("Moldurera/previsualizacionMOL",views.previsualizacionMOL,name='previsualMOL'),
    path("Reproceso/",views.ReprocesoFormView.as_view(),name='reproceso'),
    path("Reproceso/previsualizacionRPR",views.previsualizacionRPR,name='previsualRPR')
]